### ISSUE TITLE
Update "Binary Deployment" page to handle non-Linux

### ISSUE THREAD

**Issue by gconnell** [tikv/website#110]
### Describe the problem

- Relevant URL(s): https://tikv.org/docs/3.0/tasks/deploy/binary/

When visiting this page on MacOS, I get:

```
# Download the package.
wget https://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
wget http://download.pingcap.org/tidb-latest-linux-amd64.sha256
```

This doesn't work, since I'm on Mac, not Linux.  Also, trying to guess at the download doesn't seem to work.  https://download.pingcap.org/tidb-latest-linux-amd64.tar.gz contains pd-server, tikv-server, etc.  https://download.pingcap.org/tidb-latest-darwin-amd64.tar.gz just contains tidb-server, but not pd-server or tikv-server.

### Suggest an improvement/fix

1) provide links for non-Linux clients (bonus if it's automatic)
2) provide binaries for pd-server and tikv-server in darwin tar.gz binary distributions

**Comment by Hoverbear** [comment]
Hi @gconnell , it's not recommended that you deploy on Mac. Is this issue about trying to do the binary deployment onto Mac hosts, or is the issue about trying to use a Mac as the control machine?
