### ISSUE TITLE
Broken link to Community on Deep Dive page

### ISSUE THREAD

**Issue by james-jra** [tikv/website#132]
### Describe the problem

The "Community" link in the side-bar of the deep dive section is broken.
It links to https://tikv.org/contribute, which shows a Page Not Found error.

- Relevant URL(s):
  * Example page with the link: https://tikv.org/deep-dive/distributed-sql/introduction/
  * Destination page, "not found": https://tikv.org/contribute

**Comment by de-sh** [comment]
We could pull out [tikv/CONTRIBUTE.md](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md) and create the relevant page.

Otherwise seems like the mention of the link is removed and this issue is no longer relevant.

**Comment by dcalvin** [comment]
Thanks @de-sh. Actually we have plan to refactor the website recently, which including a re-purposed community page.

**Comment by dcalvin** [comment]
Close this as fixed
