### ISSUE TITLE
Broken link from Tikv Ansible Deployment

### ISSUE THREAD

**Issue by liuhao2050** [tikv/website#146]
The `Note` [from](https://tikv.org/docs/3.0/tasks/deploy/ansible/#step-5-configure-the-ssh-mutual-trust-and-sudo-rules-on-the-control-machine) linked to  [ `How to manually configure the SSH mutual trust and sudo without password`](https://github.com/pingcap/docs/blob/master/dev/how-to/deploy/orchestrated/ansible.md#how-to-manually-configure-the-ssh-mutual-trust-and-sudo-without-password) which is broken.

**Comment by de-sh** [comment]
The link has moved to [dev-guide/deploy](https://pingcap.com/docs/stable/online-deployment-using-ansible/#how-to-manually-configure-the-ssh-mutual-trust-and-sudo-without-password)

**Comment by dcalvin** [comment]
Close as solved.
