### ISSUE TITLE
RSS feed for the TiKV blog

### ISSUE THREAD

**Issue by scriptnull** [tikv/website#167]
### Describe the problem

Currently, the TiKV blog does not have an RSS/atom feed. It would be great if it is present in-order to keep up with the blog via RSS feed reader apps.

### Suggest an improvement/fix

I think it would be good to have a full RSS feed for the blog at some URL like https://tikv.org/feed.xml

**Comment by scriptnull** [comment]
I am not sure who maintains/triages things in this project. So I am tagging @WT-Liu @Hoverbear @dcalvin 

Is it ok if I send a patch for this :point_up: ?

**Comment by dcalvin** [comment]
Hi @scriptnull, Go right ahead. It would be a useful feature for the site. Thank you for offering to do this.

**Comment by dcalvin** [comment]
Close as solved.
