### ISSUE TITLE
missing sections for "Distributed SQL over TiKV"

### ISSUE THREAD

**Issue by xinglin** [tikv/website#201]
It looks like the "Distributed SQL over TiKV" should have four sections, but only has one section published now. When will you publish the other three? Really enjoyed reading several sections so far. Looking forward to reading them. Thanks,

-Xing

**Comment by WT-Liu** [comment]
@xinglin Thanks for posting the issue. Those three parts are not finished yet, but we are open to contributions. If you have ideas, please share!

**Comment by xinglin** [comment]
Alright. Do you know when they will be completed and published?

**Comment by yan-dblinf** [comment]
The introduction page about Distributed SQL is confusing because most sub-sessions are missing. Does it make sense to highlight they are to-do items?
