### ISSUE TITLE
Content is hidden without a scrolling bar

### ISSUE THREAD

**Issue by Fullstop000** [tikv/website#63]
The docs content is hidden in the small window without a horizontal scrolling bar:

![image](https://user-images.githubusercontent.com/12471960/63920649-e72c4a00-ca73-11e9-8abe-fbd3a939a0a0.png)

Maybe set `overflow-x: scroll` ?

**Comment by Hoverbear** [comment]
Yeah I've found this too. There are a few cases where this happen, notably on code blocks. (Eg the output of `docker ps` totally breaks the page layout)

I'm pretty unfamiliar with Bulma, our current CSS framework. :( Trying to make a fix.

**Comment by Hoverbear** [comment]
Fixed in #68
