### ISSUE TITLE
A link in README.md was broken

### ISSUE THREAD

**Issue by ICEYSELF** [tikv/website#64]
> This repo houses the assets used to build the [TiKV](https://github.com/tikv/website/blob/tikv) website available at https://tikv.org.

The link https://github.com/tikv/website/blob/tikv seems to be broken.

**Comment by ICEYSELF** [comment]
![图片](https://user-images.githubusercontent.com/29348140/63981226-c35b1980-caf0-11e9-8fdd-82db482d3a95.png)

**Comment by Hoverbear** [comment]
Oh no! Let me fix that, sorry!
