### ISSUE TITLE
Feature request: Entry to Doc change/request  

### ISSUE THREAD

**Issue by dcalvin** [tikv/website#65]
As open-source documentation, to facilitate the contribution/feedback is an important experience for users. So I propose we 

1. add buttons/options (Edit this page, Report an issue, Suggest doc changes) on each docs page where users can contribute any time when they spot anything while looking at a topic.  

2. Add a feedback collectiton form where users can rate, provide feedback or comment about the content. (This is less prioritized than the above one)

**Comment by Hoverbear** [comment]
Perhaps instead of rating we could ask:

"Did this page have what you were looking for?" or "Were you able to find what you were looking for?" with yes/no buttons (and a "What were you looking for?" follow up on no)

**Comment by dcalvin** [comment]
> Perhaps instead of rating we could ask:
> 
> "Did this page have what you were looking for?" or "Were you able to find what you were looking for?" with yes/no buttons (and a "What were you looking for?" follow up on no)

Yes, that would be good~ easy and straight for users.
